apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: knowledge-assistant
  labels:
    app: backend
    component: api
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: backend
