apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: knowledge-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
