apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-model-cache
  labels:
    app: vllm-server
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
