apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-data
  namespace: knowledge-assistant
  labels:
    app: ollama-server
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
