apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: knowledge-assistant
  labels:
    app: ollama-server
    component: llm-serving
spec:
  type: ClusterIP
  ports:
  - port: 11434
    targetPort: 11434
    protocol: TCP
    name: http
  selector:
    app: ollama-server
