apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-data
  namespace: knowledge-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
