apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: knowledge-assistant-dev

resources:
  - ../../base/kustomization-no-vllm.yaml

patches:
  - path: backend-deployment-patch.yaml
    target:
      kind: Deployment
      name: backend
  - path: frontend-deployment-patch.yaml
    target:
      kind: Deployment
      name: frontend

commonLabels:
  environment: dev
