apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: knowledge-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
