apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: knowledge-assistant
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: backend
        env:
        - name: LLM_PROVIDER
          value: "ollama"
        - name: OLLAMA_BASE_URL
          value: "http://ollama-service.knowledge-assistant-dev.svc.cluster.local:11434"
        - name: OLLAMA_MODEL
          value: "phi3:mini"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
