apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-server
  namespace: knowledge-assistant-dev
spec:
  template:
    spec:
      containers:
      - name: vllm-server
        # Use CPU version for dev environment
        image: vllm/vllm-openai:v0.2.7
        imagePullPolicy: IfNotPresent
        args:
        - "--model"
        - "microsoft/Phi-3-mini-4k-instruct"
        - "--host"
        - "0.0.0.0"
        - "--port"
        - "8000"
        - "--max-model-len"
        - "2048"
        - "--dtype"
        - "float32"
        - "--trust-remote-code"
        - "--served-model-name"
        - "phi-3-mini"
        - "--enforce-eager"
        - "--tensor-parallel-size"
        - "1"
        env:
        - name: CUDA_VISIBLE_DEVICES
          value: ""
        - name: CUDA_DEVICE_ORDER
          value: "PCI_BUS_ID"
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
          limits:
            memory: "8Gi"
            cpu: "4"
      # Remove all GPU-specific configurations
      nodeSelector: null
      tolerations: null
      affinity: null
