apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: milvus-data
  namespace: knowledge-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
