apiVersion: v1
kind: Service
metadata:
  name: milvus
  namespace: knowledge-assistant
  labels:
    app: milvus
    component: vector-database
spec:
  type: ClusterIP
  ports:
  - port: 19530
    targetPort: 19530
    protocol: TCP
    name: milvus
  - port: 9091
    targetPort: 9091
    protocol: TCP
    name: metrics
  selector:
    app: milvus
